name: auto-deploy

on:
  push:
    branches: [ main ]

permissions: write-all
  # contents: write
  # pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: build
        run: |
          node --version
          npm --version
          npm i -g hexo-cli
          npm i
          hexo --version
          hexo clean
          hexo generate

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
